### ISSUE TITLE
Maintainers module

### ISSUE THREAD

**Issue by puneet2019** [persistenceOne/persistenceSDK#101]
Maintainers module addition is missing in schema/applications/base/application.go := [sdkTypesModule.NewManager](https://github.com/persistenceOne/persistenceSDK/blob/master/schema/applications/base/application.go#L470) and [SetOrderInitGenesis](https://github.com/persistenceOne/persistenceSDK/blob/master/schema/applications/base/application.go#L504)

[maintainers.Module.Initialize()](https://github.com/persistenceOne/persistenceSDK/blob/master/schema/applications/base/application.go#L389) has not been given auxiliary keepers as parameters, which when given, causes looping in auxlilary, since identities transactions require maintainer auxiliary, and maintainer transactions require identities auxiliary.

and [modules/maintainers/transactions/deputize/request.go](https://github.com/persistenceOne/persistenceSDK/blob/master/modules/maintainers/transactions/deputize/request.go#L25-L27) needs govalidator fix.

**Comment by puneet2019** [comment]
#87 I think this was resolved here. @deepanshutr can you confirm and close this issue?

**Comment by aditim121** [comment]
In schema/applications/base/application.go

it is:
maintainersModule := maintainers.Module.Initialize(paramsKeeper.Subspace(metas.Module.GetDefaultParamspace()))


should be:
maintainersModule := maintainers.Module.Initialize(  paramsKeeper.Subspace(maintainers.Module.GetDefaultParamspace()), verify.Auxiliary, conform.Auxiliary)

**Comment by puneet2019** [comment]
addressed in #116 .
