### ISSUE TITLE
Unable to query transaction hash.

### ISSUE THREAD

**Issue by avkr003** [persistenceOne/persistenceSDK#102]
Getting the following response on a successful tx when querying its hash:
`{
jsonrpc: "2.0",
id: -1,
error: {
code: -32603,
message: "Internal error",
data: "runtime error: invalid memory address or nil pointer dereference"
}
}`

**Comment by puneet2019** [comment]
This comes up when the tx is not commited, and you try to query it, happens mostly in sync and async mode. @cosmos-sdk issue.
