### ISSUE TITLE
Unable to sell assets with splits, where taker gives more splits than he is supposed to

### ISSUE THREAD

**Issue by aditim121** [persistenceOne/persistenceSDK#103]
Expected Behaviour: 
excess splits should be returned to the taker.
and the asset should be exchanged.

But getting:
{"height":"1929","txhash":"2C8F3501D9405A36F787574A48F014FF4ECABD566885E6CA21B71BE09C91F785","codespace":"/xprt","code":109,"raw_log":"NotAuthorized: failed to execute message; message index: 0"}

**Comment by puneet2019** [comment]
added a semi fix in #117 , Extra splits are being returned to the taker, but in case of order going to zero, more than given taker amount could be substracted from wallet.

**Comment by puneet2019** [comment]
resolved totally in  b4be3828f8a519d3035a8f8eddf8fa9c063665c7 ,  #117
