### ISSUE TITLE
Data type of property are allowed to be of different type than what was used to create the definition of the entity.

### ISSUE THREAD

**Issue by avkr003** [persistenceOne/persistenceSDK#175]
For example, if `Identity Define` was created using the following mutable Traits `"mutableTraits":"OfficialHolidays:S|,PartyTime:S|` and while issuing an identity it is changed to `"mutableProperties":"OfficialHolidays:S|Christmas,PartyTime:H|12" ` (making `PartyTime` property from `S` type to `H` type), the transaction goes through successfully. The respective entity also takes this property with this different data type (taking `H`) under the same classification (where it is `S`). Hence this might be affecting `Meta` module too.

**Comment by puneet2019** [comment]
Changes need to be done in conform auxiliary in classification module, to also check for type.
