### ISSUE TITLE
Order Make Tx: Cannot change exchange rate once order is created without adding more makerOwnableSplit

### ISSUE THREAD

**Issue by avkr003** [persistenceOne/persistenceSDK#195]
To change only the exchange rate, giving maker ownable split value 0 fails the tx because the makerOwnableSplit is Dec{ nil } that fails the tx. Hence to change the exchange rate one has to add some amount of maker ownable to the order. Also, for assets, this becomes impossible because there is no split left to add once the order is created.

Changing  `auxiliaryRequest.Split.LTE` to `auxiliaryRequest.Split.LT` in splits/auxiliares/transfer/keeper, tx still fails when there is no split left of the ownable ID (`fromSplit` of `fromSplitID` is `nil`, as in the case of assets).

**Comment by deepanshutr** [comment]
Resolved.
