### ISSUE TITLE
NewIdentityID and NewAssetID has different input parameters.

### ISSUE THREAD

**Issue by puneet2019** [persistenceOne/persistenceSDK#201]
NewIdentityID and NewAssetID has different input parameters.

NewIdentityID (classificationID, immutablesHash)
NewAssetID ( classificationID, immutables)  //hash is calculated inside the function.

need to normalise

**Comment by ashish-jiraiya** [comment]
This issue is invalid as of master. both inputs are (classificationID types.ID, immutableProperties types.Properties).
seems to be resolved in #215 .

**Comment by puneet2019** [comment]
Oh I see, closing the issue
