### ISSUE TITLE
Staking & Sending malfunction with KEPLR & Ledger Nano X

### ISSUE THREAD

**Issue by WideAwakeTN** [persistenceOne/persistenceSDK#243]
There seems to be an issue with the Ledger Nano X and KEPLR when using the Persistence Wallet. Every time I click “approve” to initiate a transaction (for sending or staking) the transaction is immediately rejected and I get “Data is invalid : Unexpected characters”. The latest version of the ATOM app was running on the Nano X but it did not display anything special (no dialog appearing).  Setting up the Persistence wallet and connecting the Nano X through Keplr worked fine. I am using Brave 1.26.67 on Windows 10 (German locale). I also tried Ubuntu Linux with Brave and got the same issue.

**Comment by puneet2019** [comment]
@WideAwakeTN  persistence doesn't have support with ledger as of now, we are working on getting our persistence ledger App launched.

**Comment by WideAwakeTN** [comment]
I guess more people will stumble into that issue since Keplr supports connecting with Ledger Nano. Will you keep using Keplr or stop using it?

Currently some of my XPRT are stuck now since I can't create a new transaction. Will the new Ledger Nano app access the same path (on the device) / private keys? This would also solve my problem.

**Comment by WideAwakeTN** [comment]
Update: I was able to move my funds using the Brave/Chrome Keplr Plugin directly and selecting the persistence core1 chain instead of the cosmos chain. Thus it seems that the persistence web wallet frontend is the cause of the "Data is invalid : Unexpected characters" problem. 

In case you keep using Keplr I suspect the problem of signing transactions with a Ledger Nano device will also happen with your own app since it is a fork of the Zondax app.

**Comment by puneet2019** [comment]
@WideAwakeTN The persistence ledger app is launched with experimental mode, can see more about it [here](https://github.com/persistenceOne/persistenceCore/blob/master/docs/resources/Ledger.md)
you can use it directly with wallet transactions,
 keplr+ ledger support is still not there, it will take sometime to do that

**Comment by puneet2019** [comment]
@WideAwakeTN you can use keplr + ledger with [cosmostation wallet app](https://wallet.cosmostation.io). or with [keplr wallet](https://wallet.keplr.app/#/core/stake)
